In [12]:
def float_format(vector, decimal):
    return np.round((vector).astype(float), decimals=decimal)

In [11]:
from fractions import Fraction
import numpy as np

In [21]:
#(defaultProbability)
dp = Fraction(1,4)


# WWW matrix
M = np.matrix([[0, Fraction(1, 2), 0, 0],
    [Fraction(1, 3), 0, 0, Fraction(1, 2)],
    [Fraction(1, 3), 0, 0, Fraction(1, 2)],
    [Fraction(1, 3), Fraction(1, 2), 0, 0]])


E = np.zeros((4,4))
E[:] = dp

# random walk parameter 
beta = 0.85

# WWW matrix
A = beta * M + ((1-beta) * E)

# initial vector
r = np.matrix([dp, dp, dp,dp])
r = np.transpose(r)

previous_r = r
for it in range(1,100):
    r = A * r
    print (float_format(r,3))
    #check if converged
    if (previous_r==r).all():
        break
    previous_r = r

print ("Final:\n", float_format(r,3))    
print ("sum", np.sum(r))
    
## example 1.2
print ("PageRank*3:", np.round((3*r).astype(np.float), decimals=3))

[[0.144]
 [0.215]
 [0.215]
 [0.215]]
[[0.121]
 [0.161]
 [0.161]
 [0.161]]
[[0.091]
 [0.126]
 [0.126]
 [0.126]]
[[0.071]
 [0.097]
 [0.097]
 [0.097]]
[[0.055]
 [0.075]
 [0.075]
 [0.075]]
[[0.042]
 [0.058]
 [0.058]
 [0.058]]
[[0.033]
 [0.045]
 [0.045]
 [0.045]]
[[0.025]
 [0.034]
 [0.034]
 [0.034]]
[[0.019]
 [0.027]
 [0.027]
 [0.027]]
[[0.015]
 [0.021]
 [0.021]
 [0.021]]
[[0.012]
 [0.016]
 [0.016]
 [0.016]]
[[0.009]
 [0.012]
 [0.012]
 [0.012]]
[[0.007]
 [0.009]
 [0.009]
 [0.009]]
[[0.005]
 [0.007]
 [0.007]
 [0.007]]
[[0.004]
 [0.006]
 [0.006]
 [0.006]]
[[0.003]
 [0.004]
 [0.004]
 [0.004]]
[[0.002]
 [0.003]
 [0.003]
 [0.003]]
[[0.002]
 [0.003]
 [0.003]
 [0.003]]
[[0.001]
 [0.002]
 [0.002]
 [0.002]]
[[0.001]
 [0.002]
 [0.002]
 [0.002]]
[[0.001]
 [0.001]
 [0.001]
 [0.001]]
[[0.001]
 [0.001]
 [0.001]
 [0.001]]
[[0.001]
 [0.001]
 [0.001]
 [0.001]]
[[0.   ]
 [0.001]
 [0.001]
 [0.001]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]


<ipython-input-21-53ff2a74d2f1>:38: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print ("PageRank*3:", np.round((3*r).astype(np.float), decimals=3))


In [17]:
dp = Fraction(1,4)

# WWW matrix
M = np.matrix([[0,Fraction(1,2),0,0],
    [Fraction(1,3),0,0,Fraction(1,2)],
    [Fraction(1,3),0,1,Fraction(1,2)],
    [Fraction(1,3),Fraction(1,2),0,0]])

E = np.zeros((4,4))
E[:] = dp

# random walk parameter
beta = 0.85

# WWW matrix
A = beta * M + ((1-beta) * E)

# initial vector
r = np.matrix([dp, dp, dp, dp])
r = np.transpose(r)

previous_r = r
for it in range(1,100):
    r = A * r
    print(float_format(r,3))
    #check if converged
    if (previous_r==r).all():
        break
    previous_r = r

print ("Final:\n", float_format(r,3))
print ("sum", np.sum(r))
   
## example 1.2
print ("PageRank*3:", np.round((3*r).astype(float), decimals=3))

[[0.144]
 [0.215]
 [0.427]
 [0.215]]
[[0.129]
 [0.169]
 [0.532]
 [0.169]]
[[0.11 ]
 [0.146]
 [0.599]
 [0.146]]
[[0.1  ]
 [0.131]
 [0.639]
 [0.131]]
[[0.093]
 [0.121]
 [0.665]
 [0.121]]
[[0.089]
 [0.115]
 [0.68 ]
 [0.115]]
[[0.087]
 [0.112]
 [0.69 ]
 [0.112]]
[[0.085]
 [0.11 ]
 [0.696]
 [0.11 ]]
[[0.084]
 [0.108]
 [0.7  ]
 [0.108]]
[[0.083]
 [0.107]
 [0.702]
 [0.107]]
[[0.083]
 [0.107]
 [0.703]
 [0.107]]
[[0.083]
 [0.106]
 [0.704]
 [0.106]]
[[0.083]
 [0.106]
 [0.705]
 [0.106]]
[[0.083]
 [0.106]
 [0.705]
 [0.106]]
[[0.083]
 [0.106]
 [0.705]
 [0.106]]
[[0.083]
 [0.106]
 [0.706]
 [0.106]]
[[0.083]
 [0.106]
 [0.706]
 [0.106]]
[[0.083]
 [0.106]
 [0.706]
 [0.106]]
[[0.083]
 [0.106]
 [0.706]
 [0.106]]
[[0.083]
 [0.106]
 [0.706]
 [0.106]]
[[0.082]
 [0.106]
 [0.706]
 [0.106]]
[[0.082]
 [0.106]
 [0.706]
 [0.106]]
[[0.082]
 [0.106]
 [0.706]
 [0.106]]
[[0.082]
 [0.106]
 [0.706]
 [0.106]]
[[0.082]
 [0.106]
 [0.706]
 [0.106]]
[[0.082]
 [0.106]
 [0.706]
 [0.106]]
[[0.082]
 [0.106]
 [0.706]
 [0.106]]
[

In [25]:
dp = Fraction(1,5)

# WWW matrix
M = np.matrix([[0,Fraction(1,2),0,0,0],
    [Fraction(1,3),0,0,Fraction(1,2),0],
    [Fraction(1,3),0,1,Fraction(1,2),0],
    [Fraction(1,3),Fraction(1,2),0,0,0],
    [0,0,1,0,0]
    ])

E = np.zeros((5,5))
E[:] = dp

# random walk parameter
beta = 0.85

# WWW matrix
A = beta * M + ((1-beta) * E)

# initial vector
r = np.matrix([dp, dp, dp, dp,dp])
r = np.transpose(r)

previous_r = r
for it in range(1,100):
    r = A * r
    print(float_format(r,3))
    #check if converged
    if (previous_r==r).all():
        break
    previous_r = r

print ("Final:\n", float_format(r,3))
print ("sum", np.sum(r))
   
## example 1.2
print ("PageRank*3:", np.round((3*r).astype(float), decimals=3))

[[0.115]
 [0.172]
 [0.342]
 [0.172]
 [0.2  ]]
[[0.103]
 [0.136]
 [0.426]
 [0.136]
 [0.32 ]]
[[0.091]
 [0.12 ]
 [0.482]
 [0.12 ]
 [0.396]]
[[0.087]
 [0.113]
 [0.523]
 [0.113]
 [0.446]]
[[0.087]
 [0.111]
 [0.556]
 [0.111]
 [0.483]]
[[0.088]
 [0.112]
 [0.585]
 [0.112]
 [0.513]]
[[0.09 ]
 [0.115]
 [0.613]
 [0.115]
 [0.54 ]]
[[0.093]
 [0.119]
 [0.639]
 [0.119]
 [0.565]]
[[0.096]
 [0.123]
 [0.666]
 [0.123]
 [0.589]]
[[0.1  ]
 [0.127]
 [0.694]
 [0.127]
 [0.614]]
[[0.104]
 [0.132]
 [0.722]
 [0.132]
 [0.639]]
[[0.108]
 [0.138]
 [0.751]
 [0.138]
 [0.666]]
[[0.113]
 [0.143]
 [0.782]
 [0.143]
 [0.693]]
[[0.117]
 [0.149]
 [0.813]
 [0.149]
 [0.721]]
[[0.122]
 [0.155]
 [0.846]
 [0.155]
 [0.75 ]]
[[0.127]
 [0.161]
 [0.881]
 [0.161]
 [0.78 ]]
[[0.132]
 [0.168]
 [0.916]
 [0.168]
 [0.812]]
[[0.137]
 [0.174]
 [0.953]
 [0.174]
 [0.845]]
[[0.143]
 [0.182]
 [0.992]
 [0.182]
 [0.879]]
[[0.148]
 [0.189]
 [1.032]
 [0.189]
 [0.914]]
[[0.154]
 [0.196]
 [1.074]
 [0.196]
 [0.951]]
[[0.161]
 [0.204]
 [1.117]
 [0.204